import json
import datetime
import math
import numpy as np
import cv2

from simulator.terrain.orthophoto_map import OrthophotoMap
from simulator.physics.drone_state import DroneState


class CalibrationLogger:
    """
    Generates a calibration.json file compatible with the Topometric Localization system.
    Extracts the precise affine transformation from the simulator's camera projection matrix.
    Samples anchors based on significant motion (15px translation or 1.5deg rotation),
    matching the DatabaseBuilder logic.
    """

    def __init__(self, output_file: str, ortho_map: OrthophotoMap, log_interval_frames: int = 15, frame_step: int = 3):
        self.output_file = output_file
        self.ortho_map = ortho_map
        self.log_interval_frames = log_interval_frames
        self.frame_step = frame_step
        self.frame_count = 0
        self.saved_count = 0
        self.anchors = []
        
        self._last_H1 = None
        self._last_wp_idx = -1

    def log(self, H1: np.ndarray, width: int, height: int, state: DroneState, drone_lat: float, drone_lon: float, current_wp_idx: int) -> bool:
        """
        Log the calibration data when the drone reaches a new waypoint.
        Returns True if the frame was logged.
        """
        should_log = False
        
        if self._last_H1 is None:
            should_log = True
        elif current_wp_idx != self._last_wp_idx:
            should_log = True
            
        self._last_wp_idx = current_wp_idx
        
        if should_log:
            try:
                H1_inv = np.linalg.inv(H1)
            except np.linalg.LinAlgError:
                self.frame_count += 1
                return False
                
            cx, cy = width / 2.0, height / 2.0
            offset = 100.0
            pts_cam = np.array([
                [cx, cy, 1.0],
                [cx + offset, cy, 1.0],
                [cx, cy + offset, 1.0]
            ], dtype=np.float64)
            
            pts_local_hom = (H1_inv @ pts_cam.T).T
            pts_local = pts_local_hom[:, :2] / pts_local_hom[:, 2:]
            pts_mercator = pts_local + np.array([self.ortho_map._center_x, self.ortho_map._center_y])
            
            pts_cam_2d = pts_cam[:, :2].astype(np.float32)
            pts_mercator_2d = pts_mercator.astype(np.float32)
            
            affine_matrix = cv2.getAffineTransform(pts_cam_2d, pts_mercator_2d)
            center_metric = pts_mercator[0].tolist()
            now_iso = datetime.datetime.now().isoformat()
            
            anchor = {
                "frame_id": self.frame_count // self.frame_step,  # Scale index to match DatabaseBuilder p_idx
                "affine_matrix": affine_matrix.tolist(),
                "qa_data": {
                    "rmse_m": 0.0,
                    "median_err_m": 0.0,
                    "max_err_m": 0.0,
                    "inliers_count": 100,
                    "points_2d": [[cx, cy]],
                    "points_gps": [[drone_lat, drone_lon]],
                    "points_metric": [center_metric],
                    "transform_type": "simulator_ground_truth",
                    "projection_mode": "WEB_MERCATOR",
                    "created_at": now_iso,
                    "updated_at": now_iso,
                    "notes": "Generated by flight simulator",
                    "quality_flag": "normal"
                }
            }
            self.anchors.append(anchor)
            
            self._last_H1 = H1.copy()
            self._last_log_frame = self.frame_count
            self.saved_count += 1
            
        self.frame_count += 1
        return should_log

    def close(self):
        """Save the calibration JSON to disk."""
        if not self.anchors:
            print("[CalibrationLogger] No anchors recorded, skipping file creation.")
            return
            
        data = {
            "version": "2.2",
            "projection": {
                "type": "WEB_MERCATOR",
                "reference_gps": None,
                "epsg": 3857
            },
            "anchors": self.anchors
        }
        
        try:
            with open(self.output_file, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            print(f"[CalibrationLogger] Saved {len(self.anchors)} calibration anchors to {self.output_file}")
        except Exception as e:
            print(f"[CalibrationLogger] Failed to save calibration: {e}")
